services:
  web:
    build: .
    image: universe-beauty-supply
    container_name: universe-beauty
    ports:
      - "80:8080"
    restart: unless-stopped
    networks:
      - universe-network
    develop:
      watch:
        - action: sync
          path: ./index.html
          target: /usr/share/nginx/html/index.html
        - action: sync
          path: ./styles.css
          target: /usr/share/nginx/html/styles.css
        - action: sync
          path: ./script.js
          target: /usr/share/nginx/html/script.js
        - action: sync
          path: ./about_us.jpeg
          target: /usr/share/nginx/html/about_us.jpeg
        - action: sync
          path: ./background_image.jpeg
          target: /usr/share/nginx/html/background_image.jpeg
        - action: sync
          path: ./images
          target: /usr/share/nginx/html/images

networks:
  universe-network:
    driver: bridge
